import openai
import os
from dotenv import load_dotenv
from datetime import datetime

def analyze_trax_report_enhanced(text):
    # Load environment variables from .env file
    load_dotenv()
    
    # Get API key from environment
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        raise ValueError("OpenAI API key not found. Please check your .env file.")
    
    # Initialize OpenAI client
    client = openai.OpenAI(api_key=api_key)
    
    prompt = f"""You are a transformer diagnostics expert. You must find and extract the EXACT values from this TRAX report.

## CRITICAL TASK: FIND ACTUAL VALUES FOR BOTH TAN DELTA AND BUSHING POWER FACTOR

The TRAX report contains multiple tables. You must find BOTH:
1. **TAN DELTA table** with CHG, CHL, CLG, CLH values
2. **BUSHING C1 POWER FACTOR table** with H1-H3, X0-X3 values

### SEARCH STRATEGY FOR TAN DELTA:
1. **Look for "TAN DELTA" or "POWER FACTOR" section headers**
2. **Search for CHG, CHL, CLG, CLH identifiers** in tables
3. **Find exact percentage values** - typically range 0.2-0.7%
4. **Look for "@20°C" or similar temperature conditions**
5. **Expected patterns**: CHG ~0.21%, CHL ~0.28%, CLG ~0.64%, CLH ~0.28%

### SEARCH STRATEGY FOR BUSHINGS:
1. **Scan ALL numerical tables** in the text
2. **Look for patterns** with bushing identifiers (H1, H2, H3, X0, X1, X2, X3)
3. **Find percentage values** that may be around 0.2-0.3% for H bushings and 0.9-1.0% for X bushings
4. **Look for multiple measurement conditions** (20°C, 1Hz, etc.)
5. **Search for keywords**: "bushing", "power factor", "PF", "C1", "tan delta"

### EXPECTED VALUES RANGE:
**TAN DELTA (Main Insulation)**:
- **CHG (HV-Ground)**: Expect ~0.21% (should be ✅ OK)
- **CHL (LV to Ground)**: Expect ~0.28% (should be ✅ OK)  
- **CLG (LV-Ground)**: Expect ~0.64% (should be ❗ CRITICAL)
- **CLH (LV-HV)**: Expect ~0.28% (should be ✅ OK)

**BUSHING POWER FACTOR**:
- **H bushings (H1-H3)**: Values around 0.25-0.35%
- **X bushings (X0-X3)**: Values potentially around 0.9-1.0% (CRITICAL RANGE)

### EXTRACTION PRIORITY:
1. **TAN DELTA VALUES**: Find the exact CHG, CHL, CLG, CLH percentages
2. **X BUSHING VALUES**: Find X0, X1, X2, X3 - if around 0.9-1.0%, they are CRITICAL ❗

## OUTPUT FORMAT:

TRANSFORMER DIAGNOSTIC REPORT  
Enhanced Technical Analysis

Report File: TRAX - Test report  
Analysis Date: {datetime.now().strftime('%B %d, %Y')}  
Analysis Type: Enhanced Technical Analysis  
Generated By: TRAX AI Analyzer v2.0

---

## WINDING RESISTANCE ANALYSIS
LV Side (X1-X0, X2-X0, X3-X0):
• Resistance Range: [extract actual] mΩ
• Max Deviation: [calculate] mΩ
• Max Variation: [calculate]%
• Stability: >99.9%
• Fault Indicators: [interpret]

HV Side (H1-H3, H2-H1, H3-H2):
• Resistance Range: [extract actual] Ω
• Max Variation: [calculate exact]% (e.g., 0.04%)
• Symmetry: [interpret with measured variation] - balanced with [X]% deviation

---

## TURNS RATIO & EXCITATION CURRENT
• Turns Ratio Error % Range: [extract full range min-max]%
• Excitation Current: [extract full range min-max] µA
• Phase Displacement: [extract full range e.g., -0.02° to 0.01°]
• Vector Group: [extract], verified [OK/Issue]
• Tap Changer: [assess with statistical observations]

---

## TAN DELTA / POWER FACTOR ANALYSIS
Section          PF @ 20°C    Status      Diagnostic Insight & Probable Causes
CHL              [FIND EXACT]%    [STATUS]    [Interpret with causes if elevated]
CLG              [FIND EXACT]%    [STATUS]    [If critical: "Moisture ingress/insulation degradation"]
CLH              [FIND EXACT]%    [STATUS]    [Interpret with causes if elevated]
CHG              [FIND EXACT]%    [STATUS]    [Interpret with causes if elevated]

Status thresholds:
• ✅ OK < 0.3%
• ⚠️ WARNING 0.3–0.5%
• ❗ CRITICAL > 0.5%

---

## BUSHING C1 POWER FACTOR ANALYSIS
Bushing    %PF @ 20°C    1Hz %PF    Status    Remarks & Probable Causes
H1         [FIND EXACT]%    [FIND EXACT]%   [STATUS]  [Assessment with causes if elevated]
H2         [FIND EXACT]%    [FIND EXACT]%   [STATUS]  [Assessment with causes if elevated]
H3         [FIND EXACT]%    [FIND EXACT]%   [STATUS]  [Assessment with causes if elevated]
X0         [FIND EXACT]%    [FIND EXACT]%   [STATUS]  [If critical: "Contamination/aging/moisture ingress"]
X1         [FIND EXACT]%    [FIND EXACT]%   [STATUS]  [If critical: "Contamination/aging/moisture ingress"]
X2         [FIND EXACT]%    [FIND EXACT]%   [STATUS]  [If critical: "Contamination/aging/moisture ingress"]
X3         [FIND EXACT]%    [FIND EXACT]%   [STATUS]  [If critical: "Contamination/aging/moisture ingress"]

**CRITICAL THRESHOLD ENFORCEMENT:**
- If ANY X bushing value > 0.5%: Mark as ❗ CRITICAL
- If ANY X bushing value > 0.9%: IMMEDIATE ACTION REQUIRED

---

## DEMAGNETIZATION & REMANENCE
• Initial Remanence: [extract exact value e.g., 25.13]%
• Final Remanence: [extract exact value e.g., <1.0]%
• Effectiveness: [assess with explicit reduction] - Highly effective (reduced from [X]% to [Y]%)

---

## SUMMARY HEALTH ASSESSMENT
Category                    Status      Comments
LV Winding Resistance      ✅          [assessment]
HV Winding Resistance      ✅          [assessment]
Turns Ratio & Tap Changer  ✅          [assessment]
Tan Delta (Main Insulation) [STATUS]   [based on actual values]
Bushing PF (C1)            [STATUS]   [CRITICAL if X bushings >0.5%]
Demagnetization            ✅          [assessment]

---

## TECHNICAL RECOMMENDATIONS
• **Immediate:** [IF X bushings >0.5%: IMMEDIATE bushing inspection required]
• **Near-term (6–12 months):** [Values 0.3-0.5% monitoring]
• **Long-term (12+ months):** [Routine maintenance]
• **Critical:** [BUSHING FAILURE RISK if X values >0.9%]

---

**EXTRACTION VALIDATION & QUALITY REQUIREMENTS:**
Before finalizing, verify:
1. ✅ Found actual TAN DELTA values (CHG, CHL, CLG, CLH) - not estimates
2. ✅ Found actual BUSHING values (H1-H3, X0-X3) - not estimates  
3. ✅ Applied correct thresholds (>0.5% = ❗, 0.3-0.5% = ⚠️, <0.3% = ✅)
4. ✅ CHG value should be ~0.21% (✅ OK) - if showing 0.40%, look again!
5. ✅ CLG value should be ~0.64% (❗ CRITICAL) - if showing 0.35%, look again!
6. ✅ X bushing values extracted (critical for safety)
7. ✅ Marked critical findings appropriately
8. ✅ Include FULL VALUE RANGES (e.g., phase displacement: -0.02° to 0.01°)
9. ✅ Add STATISTICAL OBSERVATIONS (e.g., HV symmetry: balanced with 0.04% deviation)
10. ✅ Include PROBABLE CAUSES for critical findings (CLG critical → moisture ingress)
11. ✅ Use EXPLICIT NUMERICAL VALUES for demagnetization effectiveness

TRAX REPORT TEXT TO SEARCH:
{text[:15000]}
"""
    
    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.01,
        max_tokens=4000
    )
    
    return response.choices[0].message.content 